# 依赖的环境变量

# SONAR_TOKEN 继承全局
# SONAR_HOST_URL 继承全局
# CI_PRIVATE_TOKEN 继承全局
# K8S_NAMESPACE 项目定制化
# HARBOR 项目定制化

before_script:
  - wget https://code.avlyun.org/devops/cicd/-/raw/master/fabfilev3.py -O _ci/fabfilev3.py

stages:
  - gitcheck
  - prescan
  - prereport

unit-test:
  stage: prescan
  tags:
    - j
  script:
    - docker run --rm -v "$CI_PROJECT_DIR:/app" -w /app -e GOPROXY=https://registry-mirrors.avlyun.org/repository/goproxy/,https://goproxy.io,direct -e GOPRIVATE=*.avlyun.org -e GONOSUMDB=*.avlyun.org -e GONOPROXY=*.avlyun.org golang:1.16 go mod vendor
    - sh _ci/unittest.sh
  artifacts:
    reports:
      cobertura:
        - _ci/coverage.xml
      junit:
        - _ci/ut_report.xml
    paths:
      - _ci/coverage.out
    expire_in: 1 day
  only:
    - merge_requests
    - web

unit-test-fail:
  stage: prereport
  dependencies:
    - unit-test
  when: on_failure
  tags:
    - j
  script:
    - /usr/bin/python3 _ci/fabfilev3.py unittest_failure_report
  only:
    - merge_requests
    - web

code-lint:
  stage: prescan
  tags:
    - j
  script:
    - docker run --rm -v "$CI_PROJECT_DIR:/app" -w /app -e GOPROXY=https://registry-mirrors.avlyun.org/repository/goproxy/,https://goproxy.io,direct -e GOPRIVATE=*.avlyun.org -e GONOSUMDB=*.avlyun.org -e GONOPROXY=*.avlyun.org golang:1.16 go mod vendor
    - docker run --rm -v "$CI_PROJECT_DIR:/usr/src" -w /usr/src golangci/golangci-lint:v1.44 golangci-lint run --out-format=checkstyle --issues-exit-code=0 > _ci/report.xml
  artifacts:
    paths:
      - _ci/report.xml
    expire_in: 1 day
  only:
    - merge_requests
    - web

sonarqube:
  stage: prereport
  dependencies:
    - code-lint
    - unit-test
  tags:
    - j
  script:
    - docker run --rm -v "$CI_PROJECT_DIR:/app" -w /app -e GOPROXY=https://registry-mirrors.avlyun.org/repository/goproxy/,https://goproxy.io,direct -e GOPRIVATE=*.avlyun.org -e GONOSUMDB=*.avlyun.org -e GONOPROXY=*.avlyun.org golang:1.16 go mod vendor
    - docker run --rm -v "$CI_PROJECT_DIR:/usr/src" sonarsource/sonar-scanner-cli:latest sonar-scanner -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN -Dsonar.projectVersion=$CI_COMMIT_REF_NAME -Dsonar.projectKey=$CI_PROJECT_NAME -Dsonar.projectName="$CI_PROJECT_TITLE" -Dsonar.qualitygate.wait=true 2>&1 | tee .sonar.tmp || echo "quality gate failed"
    - /usr/bin/python3 _ci/fabfilev3.py sonar_report
  only:
    - merge_requests

# 检查代码是否从 master 拉出来的，不然不予合并，检查失败发送通知
forkMaster:
  stage: gitcheck
  tags:
    - j
  script:
    - /usr/bin/python3 _ci/fabfilev3.py is_branch_base_master
  only:
    - merge_requests
